export const articles = [
  {
    title: 'Project integration with Lighthouse CI: Quality control for every PR',
    slug: 'Project integration with Lighthouse CI: Quality control for every PR',
    excerpt: 'Use LighthouseCI GitHub Action to automatically check website quality, SEO, and improvement suggestions',
    tags: ['Lighthouse CI', 'GitHub Actions', 'SEO', 'CI/CD', 'PR Quality Control'],
    length: '5 min read',
    createdAt: 'Aug 15, 2025',
    href: 'https://medium.com/@chinghsuan1025/project-integration-with-lighthouse-ci-quality-control-for-every-pr-6ef4d3f09fbf',
  },
  {
    title: 'Frontend Perspective — Building Serverless Automated Deployment with GCP',
    slug: 'Frontend Perspective — Building Serverless Automated Deployment with GCP',
    excerpt: 'In this project, I implemented serverless automated deployment using Google Cloud Platform',
    tags: ['GCP', 'Serverless', 'Deployment', 'CI/CD'],
    length: '7 min read',
    createdAt: 'Jul 4, 2025',
    href: 'https://medium.com/@chinghsuan1025/frontend-perspective-building-serverless-automated-deployment-with-gcp-015ede4edafa',
  },
  {
    title: 'Simple Steps to Boost Your Website’s SEO Ranking',
    slug: 'Simple Steps to Boost Your Website’s SEO Ranking',
    excerpt: 'My personal understanding of the noindex, follow meta tag for crawlers.',
    tags: ['SEO', 'Ranking', 'Meta Tags', 'Crawlers'],
    length: '3 min read',
    createdAt: 'Jul 2, 2025',
    href: 'https://medium.com/@chinghsuan1025/simple-steps-to-boost-your-websites-seo-ranking-4ef897b888d4',
  },
  {
    title: 'How We Manage i18n at Scale: POEditor × GitHub Workflow',
    slug: 'How We Manage i18n at Scale: POEditor × GitHub Workflow',
    excerpt:
      'Sharing how I use POEditor and structure translation updates via Git branches — part tutorial, part work diary…',
    tags: ['i18n', 'POEditor', 'Translation'],
    length: '7 min read',
    createdAt: 'Jun 17, 2025',
    href: 'https://medium.com/@chinghsuan1025/how-we-manage-i18n-at-scale-poeditor-github-workflow-6ec995c9b922',
  },
  {
    title: 'React multi-environment build and development',
    slug: 'React multi-environment build and development',
    excerpt: 'In development, when dealing with multiple environment APIs (development, staging, production, etc.), the order of .env file resolution and how to write scripts.',
    tags: ['dotenv', 'Multi-environment', 'Webpack', '.env', 'build'],
    length: '4 min read',
    createdAt: 'Jan 15, 2023',
    href: 'https://medium.com/@chinghsuan1025/react-multi-environment-build-and-development-74317c22653d',
  },
  {
    title: 'Integrating Firebase SDK for Google OAuth Third-Party Login',
    slug: 'Integrating Firebase SDK for Google OAuth Third-Party Login',
    excerpt: 'Using Firebase SDK to implement Google OAuth third-party login, including the process of setting up Firebase and integrating it into a React application.',
    tags: ['Firebase', 'Google OAuth', 'Third-Party Login', 'React'],
    length: '4 min read',
    createdAt: 'Jan 15, 2023',
    href: 'https://medium.com/@chinghsuan1025/integrating-firebase-sdk-for-google-oauth-third-party-login-f2704bf1bd08',
  },
  {
    title: 'Why we need Axios?',
    slug: 'Why we need Axios?',
    excerpt: 'Since switching to frontend frameworks, there’s no need to rely on jQuery ajax anymore.',
    tags: ['Axios', 'Data fetching', 'API', 'Interceptors'],
    length: '5 min read',
    createdAt: 'Jan 15, 2023',
    href: 'https://medium.com/@chinghsuan1025/why-we-need-axios-91c292e775cc',
  }
];
